default['repo_directory'] = '/var/www/freegeoip-server/'
default['freegeoip_path'] = '/var/www/freegeoip-server/vendor/freegeoip-3.0.2-linux-amd64'
default['service_name'] = 'freegeoip'
default['bin_path'] = '/usr/bin/freegeoip'
default['service_path'] = '/etc/init.d/freegeoip'
